When adding a property you can mark it as output property. This way it won't mark the feature as touched when changing it. Ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=24928&p=196429#p195675

Run a BOP check AKA check the geometry using the Python API see https://forum.freecadweb.org/viewtopic.php?t=22378

Where does python search for modules on my system? (ref: https://forum.freecadweb.org/viewtopic.php?f=23&t=25499&p=202926#p202926)
> import sys
> for folder in sys.path:
>    print(folder)
Result: You will get a list of folders where python searches for modules.

How to import an IFC file via the command line (CLI) ? (ref: https://forum.freecadweb.org/viewtopic.php?f=23&t=10139&p=202920#p202920)
> import sys
> sys.path.append("/path/to/your/FreeCAD.so") # on windows it is FreeCAD.pyd instead of FreeCAD.so
> # the two above lines might be skipped if FreeCAD is in your sys.path already
> import FreeCAD
> import importIFC
> doc = importIFC.open("/path/to/your/ifcfile.ifc")
> doc.saveAs("/path/to/somename.FCStd")

Flushing report view output during run time? Run the following: (ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=25864)
> import FreeCADGui
>
> for myValue in range (0,10,1):
>     print myValue
>     FreeCADGui.updateGui()
>     # do the lengthy stuff here

Choosing Solver from the Python console (ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=24942)

How to load a .CSV file in to FreeCAD (ref: https://forum.freecadweb.org/viewtopic.php?f=3&t=30069&p=247905#p247899)

How to intersect bsplinesurface and line (ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=31043)

How to pythonically detect exclamation points (errors) in the treeview, flag name? (ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=33413#p279727)
 
How to locate the your system's default FreeCAD Macro folder? (ref: https://forum.freecadweb.org/viewtopic.php?p=338327#p338324)
> p=FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Macro")
> path_to_ui = p.GetString("MacroPath")

Using Python to automagically copy the FreeCAD "About" dialog to the clipboard: (ref: https://forum.freecadweb.org/viewtopic.php?f=22&t=23976#p187448)
